Add matrix strategy to ruby tests
hopsoft/stimulus_reflex pull request #415
Opened 2020-12-25 10:37 UTC by julianrubisch

# CI Enhancement

## Description

Version 3 seems to be not available yet, so converting this to a draft PR.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] Checks (StandardRB & Prettier-Standard) are passing
- [X] This is not a documentation update

Please note that the best way to suggest changes or updates to the [documentation](https://docs.stimulusreflex.com) is to [join Discord](https://discord.gg/XveN625) and leave a note in the #docs channel. Any documentation updates posted as PRs cannot be accepted at this time. :heart:

2020-12-25 13:28 UTC, andrewmcodes requested changes
Looks right at a glance other than my comment. 

Fwiw this is what I added for Bridgetown 

```

strategy:
      matrix:
        ruby_version: [2.5.8, 2.6.6, 2.7.2]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}

```

2020-12-25 13:28 UTC, andrewmcodes commented on .github/workflows/tests.yml
> +        ruby-version: [2.6.x, 2.7.x, 3.0.x]
You'll have to pin v3 for now.

2020-12-25 14:07 UTC, julianrubisch commented on .github/workflows/tests.yml
> +        ruby-version: [2.6.x, 2.7.x, 3.0.x]
Hmm didn’t work 😒

2021-01-07 00:46 UTC, leastbad commented
@andrewmcodes does this look good to you?

2021-01-07 01:24 UTC, andrewmcodes approved these changes
@leastbad it does. 

Great work on this @julianrubisch. This would be a great thing to share with others!

2021-01-07 04:55 UTC, merged